### ISSUE TITLE
Unable to connect to websocket stream getting error ws.close()

### ISSUE THREAD

**Issue by Aravin** [angelbroking-github/smartapi-javascript#5]
**Source**

```
let { SmartAPI, WebSocket } = require("smartapi-javascript");

let web_socket = new WebSocket({
    client_code: appConfig.angel.clientId,
    feed_token: "FEED_TOKEN",
    script: "nse_cm|2885&nse_cm|1594"   //exchange|token for multi stocks use & seperator
});

web_socket.connect();
web_socket.on('tick', receiveTick)

// TO CLOSE THE SOCKET CONNECTION
setTimeout(function () {
    web_socket.close()
}, 3000)

function receiveTick(data: any) {
    console.log("Receive stock ticks::", data)
}
```

**Error**

```
          ws.close()
             ^

TypeError: Cannot read property 'close' of null
    at WebSocket.close (D:\Playground\angle trade\node_modules\?[4msmartapi-javascript?[24m\lib\websocket.js:74:14)
    at Timeout._onTimeout (D:\Playground\angle trade\dist\index.js:40:16)
?[90m    at listOnTimeout (internal/timers.js:549:17)?[39m
?[90m    at processTimers (internal/timers.js:492:7)?[39m
```

**Comment by EVNIKHIL** [comment]
Hi @Aravin . I am trying to get the live data from API. But I am not getting any data but error. 
`/home/fingent/node/angel-broke/node_modules/smartapi-javascript/lib/websocket.js:99
          triggers[e][n].apply(triggers[e][n], args ? args : []);` 
Like this.
What is the client_code and feed token to be used here actually? I am using client_code a string "AngelOne Client ID" under the "My Profile" section in my SmartAPI login and tried feed_token as API KEY, SECRET KEY from "My Smart APIs & Apps" page then I tried "FEED_TOKEN" as string as well. What wrong I am doing ? Or data is not streaming on Sundays? Is this expected?
